### 웹툰 요청 성공
POST http://localhost:8080/v1/webtoons
Content-Type: application/json

{
  "title" : "기기괴괴",
  "writerName" : "오성대"
}

### 웹툰 요청 중 title이 20자 이상일 때 예외
POST http://localhost:8080/v1/webtoons
Content-Type: application/json

{
  "title" : "20자이상의문자열20자이상의문자열20자이상의문자열20자이상의문자열20자이상의문자열20자이상의문자열",
  "writerName" : "오성대"
}

### 웹툰 요청 중복된 title이 있는 경우 예외
POST http://localhost:8080/v1/webtoons
Content-Type: application/json

{
  "title" : "기기괴괴",
  "writerName" : "오성대"
}