spring:
    application:
        name: devtoon
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:mysql://${DEV_MYSQL_URL}
        username: ${DEV_MYSQL_USER}
        password: ${DEV_MYSQL_PASSWORD}
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
        show-sql: true
    sql:
        init:
            mode: always # data.sql 파일 실행
    cache:
        type: caffeine

jwt:
    secret: ${JWT_SECRET}
    token-validity-in-seconds: ${JWT_EXPIRED_SECONDS}

file:
    local:
        upload:
            path: ${LOCAL_IMAGE_STORAGE_URL}

